repos:
    # Ruff linting and formatting
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.3
      hooks:  
        - id: ruff
          args: [ --fix ]
        - id: ruff-format

    # Mypy type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.14.1
      hooks:
        - id: mypy
          additional_dependencies: [types-toml]

    # Gitleaks secret detection
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.16.1
      hooks:
        - id: gitleaks